name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: mkdir ~/android-env/

    - name: specify NDK
      run: |
          wget -q "https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip"
          unzip -q android-ndk-r14b-linux-x86_64.zip -d ~/android-env/

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build ijkplayer
      run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "y" | sudo apt-get install tree
          export ANDROID_NDK=~/android-env/android-ndk-r14b
          export ANDROID_NDK_ROOT=$ANDROID_NDK
          export NDK_ROOT=$ANDROID_NDK
          ./init-android.sh
          ./extra/init-extra.sh
          ./android/contrib/compile-openssl.sh
          ./android/contrib/compile-libsoxr.sh
          ./android/contrib/compile-ffmpeg.sh
          ./android/compile-ijk.sh

    - name: Upload SDK
      uses: actions/upload-artifact@v2
      with:
          name: ijkplayer
          path: ./android/build
