name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: mkdir ~/android-env/

    - name: Specify NDK
      run: |
          wget -q "https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip"
          unzip -q android-ndk-r14b-linux-x86_64.zip -d ~/android-env/

    - name: Build ijkplayer
      run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "y" | sudo apt-get install tree
          export ANDROID_NDK=~/android-env/android-ndk-r14b
          export ANDROID_NDK_ROOT=$ANDROID_NDK
          export NDK_ROOT=$ANDROID_NDK
          sh init-android.sh
          cd extra
          sh init-extra.sh
          cd ..
          cd android/contrib
          sh compile-openssl.sh all
          sh compile-libsoxr.sh all
          sh compile-ffmpeg.sh all
          cd ..
          sh compile-ijk.sh all

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: ijkplayer
          path: ./android/build
