name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: mkdir ~/android-env/

    - name: Specify NDK
      run: |
          wget -q "https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip"
          unzip -q android-ndk-r14b-linux-x86_64.zip -d ~/android-env/

    - name: Build ijkplayer
      run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "y" | sudo apt-get install tree
          export ANDROID_NDK=~/android-env/android-ndk-r14b
          export ANDROID_NDK_ROOT=$ANDROID_NDK
          export NDK_ROOT=$ANDROID_NDK
          ./init-android-openssl.sh
          ./init-android.sh
          cd extra
          ./init-extra.sh
          cd ..
          cd android/contrib
          ./compile-openssl.sh all
          ./compile-ffmpeg.sh all
          cd ..
          ./compile-ijk.sh all
          mkdir output
          cp -R ijkplayer/ijkplayer-arm64/src/main/libs/ output/ 2>/dev/null || :
          cp -R ijkplayer/ijkplayer-armv5/src/main/libs/ output/ 2>/dev/null || :
          cp -R ijkplayer/ijkplayer-armv7a/src/main/libs/ output/ 2>/dev/null || :
          cp -R ijkplayer/ijkplayer-x86/src/main/libs/ output/ 2>/dev/null || :
          cp -R ijkplayer/ijkplayer-x86_64/src/main/libs/ output/ 2>/dev/null || :

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: ijkplayer
          path: ./android/output
